### ISSUE TITLE
CI Improvement Plan

### ISSUE THREAD

**Issue by dguido** [trailofbits/buttercup#108]
Current CI Issues:
- Unit tests and Docker builds failing
- Integration tests failing

Performance Bottlenecks:
- Integration tests can take >2 hours with multiple 25-minute timeouts
- Sequential matrix builds for 6 components
- No parallelization optimization for Docker builds

Main Recommendations:
1. Immediate: Fix failing tests in common component and patcher Docker build
2. High Priority: Separate unit/integration tests, enable parallel builds
3. Medium Priority: Simplify integration tests, add retry logic, improve monitoring
4. Long-term: Better configuration management, developer tooling

**Comment by dguido** [comment]
# CI/CD Pipeline Improvement Recommendations

## Current State Analysis

### Workflow Overview
The project has 4 main CI workflows:
1. **Lint** - Runs ruff and mypy on all Python components
2. **Unit tests** - Runs pytest for all components with integration tests
3. **Docker Build and Push** - Builds and pushes Docker images for 5 components
4. **Docker Compose integration tests** - Complex end-to-end integration testing

### Current Issues

#### 1. Recent Failures (as of June 2025)
- **Unit tests** failing since June 25, 2025 (common component)
- **Docker Build** failing since June 25, 2025 (patcher component)
- **Integration tests** consistently failing since June 25, 2025
- Last successful full CI run was in April 2025

#### 2. Performance Bottlenecks
- **Integration tests** have multiple long timeouts:
  - Fuzzer build: 25 minutes
  - Vulnerability finding: 25 minutes
  - Patch submission: 25 minutes
  - Seed generation: 25 minutes
  - Total potential runtime: >2 hours
- **Matrix builds** run sequentially for 6 components in tests
- **Docker builds** for 5 components without parallelization optimization

#### 3. Configuration Issues
- Integration tests depend on external Kubernetes cluster with secrets
- Complex environment setup with 20+ environment variables
- No clear separation between unit and integration tests
- GraphDB service configuration commented out in tests.yml

## Recommendations

### 1. Fix Immediate Failures
- **Priority: Critical**
- Investigate and fix the failing tests in the common component
- Fix the Docker build issue in the patcher component
- Consider temporarily disabling integration tests until stabilized

### 2. Improve Test Organization
- **Priority: High**
- Separate unit tests from integration tests into different workflows
- Add smoke tests that run quickly on every PR
- Create a nightly workflow for long-running integration tests
- Add test result reporting and failure notifications

### 3. Optimize Build Performance
- **Priority: High**
- Enable parallel matrix builds by increasing runner count
- Use Docker layer caching more effectively
- Consider using larger GitHub Actions runners for builds
- Implement conditional builds (only build changed components)

### 4. Simplify Integration Tests
- **Priority: Medium**
- Replace Kubernetes dependency with Docker Compose for CI
- Reduce timeout values or make them configurable
- Add early exit conditions for faster failure detection
- Mock external dependencies where possible

### 5. Improve Workflow Reliability
- **Priority: Medium**
- Add retry logic for flaky tests
- Implement better error reporting and logging
- Add workflow status badges to README
- Create a CI health dashboard

### 6. Configuration Management
- **Priority: Low**
- Use GitHub Environments for secret management
- Reduce number of required environment variables
- Document all CI configuration requirements
- Add validation for required secrets

### 7. Developer Experience
- **Priority: Low**
- Add pre-commit hooks for local linting
- Create development containers matching CI environment
- Add CI debugging documentation
- Implement PR preview environments

## Implementation Plan

### Phase 1: Stabilization
1. Fix current test failures
2. Separate unit and integration tests
3. Disable/fix flaky integration tests

### Phase 2: Optimization
1. Implement parallel builds
2. Add caching strategies
3. Optimize Docker builds

### Phase 3: Enhancement
1. Add monitoring and reporting
2. Implement advanced features
3. Documentation and tooling

## Example Workflow Improvements

### Optimized Unit Test Workflow
```yaml
name: Unit Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        component: [common, orchestrator, fuzzer, program-model, seed-gen, patcher]
      fail-fast: false
      max-parallel: 6  # Run all in parallel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
      - name: Run tests
        run: |
          uv sync --frozen
          uv run pytest -v --tb=short
```

### Staged Docker Build
```yaml
name: Docker Build
on: [push, pull_request]
jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.changes.outputs.components }}
    steps:
      - uses: actions/checkout@v4
      - id: changes
        run: |
          # Detect which components changed
          echo "components=$(./scripts/detect-changes.sh)" >> $GITHUB_OUTPUT
  
  build:
    needs: changed-files
    if: needs.changed-files.outputs.components != '[]'
    strategy:
      matrix:
        component: ${{ fromJson(needs.changed-files.outputs.components) }}
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

The CI pipeline has significant room for improvement in reliability, performance, and maintainability. By implementing these recommendations in phases, the team can achieve a more stable and efficient development workflow while reducing CI-related delays and frustrations.
